backend:
  name: git-gateway
  branch: master
  commit_messages:
  create: "Create {{collection}} “{{slug}}”"
  update: "Update {{collection}} “{{slug}}”"
  delete: "Delete {{collection}} “{{slug}}”"
  uploadMedia: "[skip ci] Upload “{{path}}”"
  deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: content/blog-posts
    create: true
    fields:
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Links"
        name: "links"
        file: "content/pages/links.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "links-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/links" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Index"
        name: "index"
        file: "content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/index" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ""
                required: false
              - widget: image
                name: image
                label: image
                default: "/assets/stackrole.png"
              - widget: image
                name: iconimage
                label: favicon
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false
          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
      - label: Social Icons
        name: socialIcons
        file: "src/util/socialmedia.json"
        fields:
          - label: Social Icons
            name: socialIcons
            widget: list
            collapsed: true
            hint: "Here you can add social icons, Click on 'Add social icons'"
            fields:
              - label: "Icons"
                name: "icon"
                widget: "select"
                options:
                  [
                    "facebook",
                    "twitter",
                    "linkedin",
                    "youtube",
                    "instagram",
                    "rss",
                    "github",
                    "telegram",
                    "pinterest",
                    "snapchat",
                    "skype",
                    "wordpress",
                    "dribbble",
                    "medium",
                    "behance",
                    "vk",
                  ]
                hint: "Select the Icon"
              - widget: string
                name: url
                label: url
                required: true
                hint: "Paste the 'URL' of your Social media"
