backend:
  name: git-gateway
  branch: master
  commit_messages:
  create: "Create {{collection}} “{{slug}}”"
  update: "Update {{collection}} “{{slug}}”"
  delete: "Delete {{collection}} “{{slug}}”"
  uploadMedia: "[skip ci] Upload “{{path}}”"
  deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
